name: Semgrep

on:
  workflow_dispatch: {}
  pull_request: {}

permissions:
  contents: read

jobs:
  semgrep-latest:
    name: sem
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep:latest
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4
      - run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
          SEMGREP_REPO_DISPLAY_NAME: 'juice-shop-latest'

  semgrep-138:
    name: grep
    runs-on: ubuntu-latest
    container:
      image: 'semgrep/semgrep:1.138.0'
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4
      - run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
          SEMGREP_REPO_DISPLAY_NAME: 'juice-shop-138'
          
